/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
#include "AppDelegate.h"
#include "com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper.h"
#include "cocos2d.h"
#include "UpArpuListenerManager.h"
#include "UpArpuUtil.h"

/* Header for class com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper */

#ifndef _Included_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_imp
#define _Included_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_imp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerLoaded
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {

    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosBannerAdListener *bannerAdListener = UpArpuListenerManager::getInstance()->getBannerListener(
            placementId);
    if (bannerAdListener != NULL) {
        bannerAdListener->onBannerAdLoadSuccess(placementId);
    }

}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerFailed
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring, jstring errorMsg) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosBannerAdListener *bannerAdListener = UpArpuListenerManager::getInstance()->getBannerListener(
            placementId);
    if (bannerAdListener != NULL) {
        bannerAdListener->onBannerAdLoadFailed(placementId, errorString);
    }

}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerClicked
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosBannerAdListener *bannerAdListener = UpArpuListenerManager::getInstance()->getBannerListener(
            placementId);
    if (bannerAdListener != NULL) {
        bannerAdListener->onBannerClicked(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerShow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerShow
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosBannerAdListener *bannerAdListener = UpArpuListenerManager::getInstance()->getBannerListener(
            placementId);
    if (bannerAdListener != NULL) {
        bannerAdListener->onBannerShow(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerClose
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosBannerAdListener *bannerAdListener = UpArpuListenerManager::getInstance()->getBannerListener(
            placementId);
    if (bannerAdListener != NULL) {
        bannerAdListener->onBannerClose(placementId);
    }
}

/*
* Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
* Method:    onBannerClose
* Signature: ()V
*/
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerAutoRefreshed
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosBannerAdListener *bannerAdListener = UpArpuListenerManager::getInstance()->getBannerListener(
            placementId);
    if (bannerAdListener != NULL) {
        bannerAdListener->onBannerAutoRefresh(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerAutoRefreshFail
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring, jstring errorMsg) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosBannerAdListener *bannerAdListener = UpArpuListenerManager::getInstance()->getBannerListener(
            placementId);
    if (bannerAdListener != NULL) {
        bannerAdListener->onBannerAutoRefreshFail(placementId, errorString);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdLoaded
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosInterstitialAdListener *interstitialAdListener = UpArpuListenerManager::getInstance()->getInterstitialListener(
            placementId);
    if (interstitialAdListener != NULL) {
        interstitialAdListener->onInterstitalLoadSuccess(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdLoadFail
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdLoadFail
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring, jstring errorMsg) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosInterstitialAdListener *interstitialAdListener = UpArpuListenerManager::getInstance()->getInterstitialListener(
            placementId);
    if (interstitialAdListener != NULL) {
        interstitialAdListener->onInterstitalLoadFailed(placementId, errorString);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdClicked
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosInterstitialAdListener *interstitialAdListener = UpArpuListenerManager::getInstance()->getInterstitialListener(
            placementId);
    if (interstitialAdListener != NULL) {
        interstitialAdListener->onInterstitalClicked(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdShow
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdShow
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosInterstitialAdListener *interstitialAdListener = UpArpuListenerManager::getInstance()->getInterstitialListener(
            placementId);
    if (interstitialAdListener != NULL) {
        interstitialAdListener->onInterstitalShow(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdClose
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosInterstitialAdListener *interstitialAdListener = UpArpuListenerManager::getInstance()->getInterstitialListener(
            placementId);
    if (interstitialAdListener != NULL) {
        interstitialAdListener->onInterstitalClose(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdVideoStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdVideoStart
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdVideoEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdVideoEnd
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdVideoError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdVideoError
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring, jstring errorMsg) {
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdLoaded
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosRewardedVideoAdListener *rewardedVideoAdListener = UpArpuListenerManager::getInstance()->getRewardedVideoListener(
            placementId);
    if (rewardedVideoAdListener != NULL) {
        rewardedVideoAdListener->onRewardedVideoLoadSuccess(placementId);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdFailed
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring, jstring errorMsg) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosRewardedVideoAdListener *rewardedVideoAdListener = UpArpuListenerManager::getInstance()->getRewardedVideoListener(
            placementId);
    if (rewardedVideoAdListener != NULL) {
        rewardedVideoAdListener->onRewardedVideoLoadFailed(placementId, errorString);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayStart
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {

    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosRewardedVideoAdListener *rewardedVideoAdListener = UpArpuListenerManager::getInstance()->getRewardedVideoListener(
            placementId);
    if (rewardedVideoAdListener != NULL) {
        rewardedVideoAdListener->onRewardedVideoPlayStart(placementId);
    }

}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayEnd
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {

    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosRewardedVideoAdListener *rewardedVideoAdListener = UpArpuListenerManager::getInstance()->getRewardedVideoListener(
            placementId);
    if (rewardedVideoAdListener != NULL) {
        rewardedVideoAdListener->onRewardedVideoPlayEnd(placementId);
    }

}


/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayFailed
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring, jstring errorMsg) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosRewardedVideoAdListener *rewardedVideoAdListener = UpArpuListenerManager::getInstance()->getRewardedVideoListener(
            placementId);
    if (rewardedVideoAdListener != NULL) {
        rewardedVideoAdListener->onRewardedVideoShowFail(placementId, errorString);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdClosed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdClosed
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring, jboolean isReward) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosRewardedVideoAdListener *rewardedVideoAdListener = UpArpuListenerManager::getInstance()->getRewardedVideoListener(
            placementId);
    if (rewardedVideoAdListener != NULL) {
        rewardedVideoAdListener->onRewardedVideoClose(placementId, isReward == JNI_TRUE);
    }
}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayClicked
        (JNIEnv *pEven, jclass pJclass, jstring placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosRewardedVideoAdListener *rewardedVideoAdListener = UpArpuListenerManager::getInstance()->getRewardedVideoListener(
            placementId);
    if (rewardedVideoAdListener != NULL) {
        rewardedVideoAdListener->onRewardedVideoClicked(placementId);
    }
}

JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdLoaded
        (JNIEnv *pEven, jclass pJclass, jstring
        placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeAdListener *nativeAdListener = UpArpuListenerManager::getInstance()->getNativeListener(
            placementId);
    if (nativeAdListener != NULL) {
        nativeAdListener->onNativeAdLoadSuccess(placementId);
    }

}

JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdLoadFail
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring, jstring errorMsg
        ) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosNativeAdListener *nativeAdListener = UpArpuListenerManager::getInstance()->getNativeListener(
            placementId);
    if (nativeAdListener != NULL) {
        nativeAdListener->onNativeAdLoadFailed(placementId, errorString);
    }


}

JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdShow
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeAdListener *nativeAdListener = UpArpuListenerManager::getInstance()->getNativeListener(
            placementId);
    if (nativeAdListener != NULL) {
        nativeAdListener->onNativeAdShow(placementId);
    }
}

JNIEXPORT void JNICALL
Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdClick
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring) {
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeAdListener *nativeAdListener = UpArpuListenerManager::getInstance()->getNativeListener(
            placementId);
    if (nativeAdListener != NULL) {
        nativeAdListener->onNativeAdClick(placementId);
    }
}


/**---------------------------------------------------Native Banner----------------------------------------------------------------------**/

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdLoaded
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring){
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeBannerAdListener *nativeBannerAdListener = UpArpuListenerManager::getInstance()->getNativeBannerAdListener(
            placementId);
    if (nativeBannerAdListener != NULL) {
        nativeBannerAdListener->onNativeBannerAdLoadSuccess(placementId);
    }
}

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdLoadFail
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring, jstring errorMsg){
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosNativeBannerAdListener *nativeBannerAdListener = UpArpuListenerManager::getInstance()->getNativeBannerAdListener(
            placementId);
    if (nativeBannerAdListener != NULL) {
        nativeBannerAdListener->onNativeBannerAdLoadFailed(placementId, errorString);
    }
}

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdClick
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring){
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeBannerAdListener *nativeBannerAdListener = UpArpuListenerManager::getInstance()->getNativeBannerAdListener(
            placementId);
    if (nativeBannerAdListener != NULL) {
        nativeBannerAdListener->onNativeBannerClicked(placementId);
    }
}

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdShow
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring){
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeBannerAdListener *nativeBannerAdListener = UpArpuListenerManager::getInstance()->getNativeBannerAdListener(
            placementId);
    if (nativeBannerAdListener != NULL) {
        nativeBannerAdListener->onNativeBannerShow(placementId);
    }
}

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdClose
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring){
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeBannerAdListener *nativeBannerAdListener = UpArpuListenerManager::getInstance()->getNativeBannerAdListener(
            placementId);
    if (nativeBannerAdListener != NULL) {
        nativeBannerAdListener->onNativeBannerClose(placementId);
    }
}

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdAutoRefreshed
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring){
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    UpArpuCocosNativeBannerAdListener *nativeBannerAdListener = UpArpuListenerManager::getInstance()->getNativeBannerAdListener(
            placementId);
    if (nativeBannerAdListener != NULL) {
        nativeBannerAdListener->onNativeBannerAutoRefresh(placementId);
    }
}

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdAutoRefreshFail
        (JNIEnv
         *pEven,
         jclass pJclass, jstring
         placementIdJstring, jstring errorMsg){
    char *placementId = UpArpuUtil::jstringTostring(pEven, placementIdJstring);
    char *errorString = UpArpuUtil::jstringTostring(pEven, errorMsg);
    UpArpuCocosNativeBannerAdListener *nativeBannerAdListener = UpArpuListenerManager::getInstance()->getNativeBannerAdListener(
            placementId);
    if (nativeBannerAdListener != NULL) {
        nativeBannerAdListener->onNativeBannerAutoRefreshFail(placementId, errorString);
    }
}
/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onSDKInitSuccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onSDKInitSuccess
        (JNIEnv *pEven, jclass
        pJclass,
         jstring pJstring
        ) {

}

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onSDKInitFail
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onSDKInitFail
        (JNIEnv *pEven, jclass
        pJclass,
         jstring pJstring
        ) {

}

#ifdef __cplusplus
}
#endif
#endif
