/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper */

#ifndef _Included_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
#define _Included_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerLoaded
 (JNIEnv *, jclass, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerFailed
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerClicked
 (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerShow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerShow
 (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerClose
 (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerAutoRefreshed
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onBannerClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onBannerAutoRefreshFail
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdLoaded
 (JNIEnv *, jclass, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdLoadFail
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdLoadFail
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdClicked
 (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdShow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdShow
 (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdClose
 (JNIEnv *, jclass, jstring, jstring);



/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdVideoStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdVideoStart
 (JNIEnv *, jclass, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdVideoEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdVideoEnd
 (JNIEnv *, jclass, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onInterstitialAdVideoError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onInterstitialAdVideoError
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdLoaded
 (JNIEnv *, jclass, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdFailed
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayStart
 (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayEnd
 (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayFailed
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdClosed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdClosed
  (JNIEnv *, jclass, jstring, jboolean, jstring);

/*
 * Class:     com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper
 * Method:    onRewardedVideoAdPlayClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onRewardedVideoAdPlayClicked
 (JNIEnv *, jclass, jstring, jstring);



JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdLoaded
        (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdLoadFail
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdShow
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeAdClick
        (JNIEnv *, jclass, jstring, jstring);



/**---------------------------------------------------Native Banner----------------------------------------------------------------------**/

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdLoaded
        (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdLoadFail
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdClick
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdShow
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdClose
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdAutoRefreshed
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onNativeBannerAdAutoRefreshFail
        (JNIEnv *, jclass, jstring, jstring, jstring);



JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onSDKInitSuccess
 (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onSDKInitFail
  (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onGdprAuth
        (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onPageLoadFail
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_uparpu_cocos2dx_bridge_UpArpuListenerEventJniHelper_onUserLocation
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
